<!DOCTYPE html>
<html lang="zh">
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="Pragma" content="no-cache">
		<meta http-equiv="Cache-Control" content="no-cache,must-revaildate">
		<meta http-equiv="expires" content="0">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> 
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>预言家系统</title>
		<link rel="stylesheet" type="text/css" href="/css/base.css"/>
		<link rel="stylesheet" type="text/css" href="/css/default.css">
	    <link rel="shortcut icon" type="image/x-icon" href="/images/logo.png"/>
		<!--必要样式-->
		<link rel="stylesheet" type="text/css" href="/css/style.css">
		<link rel="stylesheet" type="text/css" href="/css/laydate.css"/>
		<link rel="stylesheet" type="text/css" href="/css/skin.css"/>
		<link rel="stylesheet" type="text/css" href="/css/loading.css"/>
		<style type="text/css">
	        .icon {
	          /* 通过设置 font-size 来改变图标大小 */
	          width: 1em; height: 1em;
	          /* 图标和文字相邻时，垂直对齐 */
	          vertical-align: -0.15em;
	          /* 通过设置 color 来改变 SVG 的颜色/fill */
	          fill: currentColor;
	          /* path 和 stroke 溢出 viewBox 部分在 IE 下会显示
	             normalize.css 中也包含这行 */
	          overflow: hidden;
	        }
	        .index-leftBox li:nth-of-type(2) .icon{
				top: 23px;
				transform: scale(1.6);
			}
	        .index-leftBox li:nth-of-type(4) .icon,
			.index-leftBox li:nth-of-type(5) .icon{
				top: 23px;
				transform: scale(1.7);
			}
    	</style>
	</head>
	<body>
		<div class="index-container">
			<!--header start-->
			<header class="clearfix" style="box-shadow: 0px -2px 26px -5px #607D8B;">
				<h3 class="title-logo">
					<img src="images/logo.png"/>
					<i style="vertical-align: super;">预言家系统</i>
				</h3>
				<ul class="in_right login">
					<li>
						<svg class="icon" aria-hidden="true" style="transform: scale(1.4);">
	                        <use xlink:href="#icon-user-outline"></use>
	                    </svg>
					</li>
					<li>用户:</li>
					<li class="login_one "><a href="javascript:;" id="userName"></a></li>
					<li><a href="javascript:;" id="Logout" onclick="exit()">退出登录</a></li>
				</ul>
			</header>
			<!--header end-->
			<!--LeftBox start-->
			<aside class="index-leftBox navItems">
				<ul class="mainmenu">
					<li id="105">
						<svg class="icon" aria-hidden="true">
	                        <use xlink:href="#icon-shouye-shouye"></use>
	                    </svg>
						<span>首页</span>
					</li>
					<li id="105">
						<svg class="icon" aria-hidden="true">
	                        <use xlink:href="#icon-dingqilicai"></use>
	                    </svg>
						<span>定期到期</span>
					</li>
					<li id="106">
						<svg class="icon" aria-hidden="true">
	                        <use xlink:href="#icon-duihuan"></use>
	                    </svg>
						<span>兑付</span>
					</li>
					<li id="107">
						<svg class="icon" aria-hidden="true">
	                        <use xlink:href="#icon-shuhuia"></use>
	                    </svg>
						<span>活期赎回</span>
					</li>
					<li id="108">
						<svg class="icon" aria-hidden="true">
	                        <use xlink:href="#icon-lvqiatonghuoqizhuandingqi"></use>
	                    </svg>
						<span>活包定到期</span>
					</li>
					<li id="109">
						<svg class="icon" aria-hidden="true">
	                        <use xlink:href="#icon-shichang"></use>
	                    </svg>
						<span>二级市场到期</span>
					</li>
					<li id="110">
						<svg class="icon" aria-hidden="true">
	                        <use xlink:href="#icon-demo15"></use>
	                    </svg>
						<span>新交易用户</span>
					</li>
				</ul>
			</aside>
			<!--LeftBox end-->
			<!--RightBox strat-->
			<div class="g-content">
				<section class="main atPresent-main m-chart">
					<div class="chart-items">
						<section id="recentlyExpired" class="chart">
							<article class="loading" id="chartLoading1"></article>
						</section>
						<section id="recentlySixMonths" class="chart">
							<article class="loading" id="chartLoading2"></article>
						</section>
					</div>
				</section>
				<section class="main m-svg"></section>	
			</div>
			<aside class="index-rightBox"></aside>
		    <!--RightBox end-->
		</div>
		<!-- 日期选项 -->
        <div id="date-query">
            <form >
            	<section class="submenu">
	                <input type="text" value="" placeholder="请输入到期开始日期" onClick="c = laydate({istime: true, format: 'YYYY-MM-DD'})">
	            	<input type="text" value="" placeholder="请输入到期结束日期" onClick="laydate({istime: true, format: 'YYYY-MM-DD'})">
	                <hr />
	                <input type="text" value="" placeholder="请输入跟踪开始时间" class="laydate-icon" onClick="laydate({istime: true, format: 'YYYY-MM-DD hh:mm:ss'})">
	            	<input type="text" value="" placeholder="请输入跟踪结束时间" class="laydate-icon" onClick="laydate({istime: true, format: 'YYYY-MM-DD hh:mm:ss'})">
	            </section>
                <input type="button" value="提交" class="submit" style="cursor: pointer;"/>
            </form>
        </div>
        <div id="overText"><!-- 详细类数据显示 金额&人数  --></div>
	</body>
	<script type="text/javascript" src="/js/iconfont.js"></script>
	<script type="text/javascript" src="/js/laydate.js"></script><!-- iconfont -->
	<script type="text/javascript" src="/js/jquery-2.1.1.min.js"></script>
	<script type="text/javascript" src="/js/jquery.cookie.js"></script>
	<script type="text/javascript" src="/js/d3.v4.min.js"></script>
	<script type="text/javascript" src="/js/tools.js"></script>
	<script type="text/javascript" src="/js/echarts.min.js"></script>
	<script type="text/javascript" src="/js/baseStyle.js"></script>
	<script type="text/javascript" src="/js/submit.js"></script>
	<script type="text/javascript">
		var c = null;
		var dataUser = $.cookie('US_SESSION_ID'); 
		$('#userName').html($.cookie('fuser'));
		$(document).ready($('#userName').html($.cookie('fuser')))
		// 退出登录
		function exit() {
		    var date = new Date();
		    date.setTime(date.getTime() - 10000);
		    document.cookie = 'pp'    + "=" + null + "; expires=" + date.toGMTString();
		    document.cookie = 'user'  + "=" + null + "; expires=" + date.toGMTString();
		    document.cookie = 'puser' + "=" + null + "; expires=" + date.toGMTString();
		    document.cookie = 'pec'   + "=" + null + "; expires=" + date.toGMTString();
		    document.cookie = 's'     + "=" + null + "; expires=" + date.toGMTString();
		    document.cookie = 'fuser' + "=a; expires=" + date.toGMTString();
		    location.href='/login';
		}
	</script>
</html>