<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<!-- 优先使用最新版本IE & Chrome -->
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
		<!-- 360使用Chrome Frame -->
		<meta name="renderer" content="webkit">
		<!-- 360 使用 Chrome内核 -->
		<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
		<!-- `width=device-width` 会导致 iPhone 5 添加到主屏后以 WebApp 全屏模式打开页面时出现黑边 http://bigc.at/ios-webapp-viewport-meta.orz -->
		<meta name ="viewport" content ="width=device-width,initial-scale=0.5, maximum-scale=1, minimum-scale=0.5, user-scalable=yes">
		<!-- 禁止数字识自动别为电话号码 -->
		<meta name="format-detection" content="telephone=no"/>
		<title></title>
		<!--<meta name="viewport" content="initial-scale=1, maximum-scale=1">-->
		<link rel="stylesheet" type="text/css" href="/icon-fonts/iconfont.css">
		<link rel="stylesheet" type="text/css" href="/js/light7/light7.min.css">
		<link rel="stylesheet" type="text/css" href="/css/base.css"/>
		<style type="text/css">
			body {
				height: 100%;
				overflow: hidden;
				background-color: black !important;
			}
			.page-group {
				position: relative;
			}
			.nav{
				position: absolute;
				top: 0;
				right: 0;
				bottom: 0;
				left: 0;
				margin: auto;
				width: 250px;
				height: 500px;
			}
			.nav .nav_content{
				width: 100%;
				height: 100%;
				padding: 40px 20px;
				position: relative;
			}
			.nav_content a{
				position: relative;
				display: block;
				width: 100%;
				height: 50%;
			}
			/*.nav_content a:nth-of-type(1):after{
				position: absolute;
				content: "";
				width: 40%;
				height: 2px;
				left: 30%;
				bottom: 0;
				border-radius: 50%;
				background-color: #666;
				box-shadow: 0 1px 6px 1px #a08b8b;
			}*/
		</style>
	</head>
	<body>
		<div class="page-group" style="width: 100%;height: 100%; background: url(/image/navBg.jpg) no-repeat center center / auto 110%;">
			<div class="nav">
				<section class="nav_content">
					<a target="_blank" href="http://dp.xiwanglife.com" id="parPage"></a>
					<a target="_blank" href="http://rp.xiwanglife.com" id="nextPage"></a>
				</section>
			</div>
		</div>
	</body>
	<script type='text/javascript' src='/js/jquery.min.js'></script>
	<script type="text/javascript" src="/js/tools.js"></script>
	<script type="text/javascript" src="/js/bar.js"></script>
	<script src="/js/jquery.cookie.js"></script>
	<script type="text/javascript" src="/js/canvas.js"></script>
	<script type="text/javascript" src="/js/d3.v4.min.js"></script>
	<script type="text/javascript" src="/js/global.js"></script>
	<script type="text/javascript" src="/js/hammer.min.js"></script>
	<script type="text/javascript" src="/js/echarts.min.js"></script>
	<script src="/js/city.js" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript">
		var w = document.body.offsetWidth, // 可视窗口高度
			h = document.body.offsetHeight;
		var sw = window.screen.width, // screen 分辨率
			sh = window.screen.height;
			
			
			
			myCanvas('parPage',[
				{
					"path"		: ["0,2","0,2"],
					"width"		: ["5","10"],
					"radii"		: ["w/2-30","w/2-50"],
					"speed"		: ["1"],
					"color"		: ["hsla(164,100%,23%,1)","hsla(164,100%,23%,.3)"],
					"type"		: "arc"
				},/*{
					"radii"		: ["w*0.04,w/2-40"],
					"path"		: ["0,2"],
					"width"		: ["2"],
					"color"		: ["hsla(164,100%,23%,1),hsla(184,100%,49%,.1)"],
					"type": "circle"
				},*/{
					"texts" 	: ['D'],
					"font" 		: ["normal 600 70px arial black "],
					"color"		: ["#59d5ef"],
					"type" 		: "Test"
				}
			],false,'After');
			
			myCanvas('nextPage',[
				{
					"path"		: ["0,2"],
					"width"		: ["5"],
					"radii"		: ["w/2-30"],
					"speed"		: ["1"],
					"color"		: ["hsla(164,100%,23%,1)"],
					"type"		: "arc"
				}/*,{
					"radii"		: ["w*0.04,w/2-40"],
					"path"		: ["0,2"],
					"width"		: ["2"],
					"color"		: ["hsla(164,100%,23%,1),hsla(184,100%,49%,.1)"],
					"type": "circle"
				}*/,{
					"texts" 	: ["R"],
					"font" 		: ["normal 600 70px arial black  "],
					"color"		: ["#59d5ef"],
					"type" 		: "Test"
				}
			],false,'After');
			
			
			
			
			
			
			
			
			
			
			
		// 获取数据
		/*==============  touch ===================*/
		/*var touchXStart,
			touchYStart;
		
		$(document).bind("touchstart", function(e) {
			var touch = e.originalEvent.targetTouches[0];
			touchXStart = touch.pageX;
			touchYStart = touch.pageY;
			event.preventDefault();
		});
		$(document).bind("touchend", touchEnd);
		
		function touchEnd(e) {
			var id = null;
			var touch = e;
			if(e.originalEvent.targetTouches.length > 0) return;
			if(e.originalEvent && e.originalEvent.changedTouches) {
				touch = e.originalEvent.changedTouches[0];
			}

            id = $('.page-current').first();
			if(touchXStart - touch.pageX > 100) {
				if(id.find('.nextPage').length < 1) return;
				id.find('.nextPage').trigger("click");
			} else if(touch.pageX - touchXStart > 100) {
				if(id.find('.prePage').length < 1) return;
				id.find('.prePage').trigger("click");
			}
		}
		// flicker
		setInterval(function() {
			$('.flicker1').toggle(1500);
			$('.flicker2').toggle(1500);
		}, 1500);
		*/
		
	</script>
</html>