<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=9">
        <title>实时报表系统登录</title>

        <link rel="stylesheet" type="text/css" href="/js/semantic/semantic.min.css">
        <script type="text/javascript" src="/js/jquery.min.js"></script>
        <script src="/js/semantic/semantic.min.js"></script>

        <style>
            body {
                font-family: Verdana,Arial,Helvetica,sans-serif;
                margin: 0;
                background-color:#fff;
            }
            .ui.grid{
                margin:0;
            }
            .header-row1{
                height:50px;
            }
            .login-header {
                background-color: #0066b1;
                height: 160px;

            }

            .ui.white {
                color: #fff;
            }
            .text-center{
                text-align:center;
            }

            .ui.login-div{
                margin:30px 0 0 0;
            }
        </style>
        <script>

            $(document).ready(function () {
                $("#submit").click(function () {
                    var name = $("#username").val();
                    var pass = $("#password").val();
                    $.ajax({
                        url: "/login/doLogin",
                        async: true,
                        type: 'POST',
                        data: {name: name, pass: pass},
                        success: function (text, textStatus) {
                           
                            var o = jQuery.parseJSON(text);
                            if (o.c === 0) {
                                window.location.href = o.t;
                            } else if (o.c === -1) {
                                $("#message").text(o.t);
                            }
                        }
                    });
                });
            });

        </script>

    </head>
    <body>
        <div class="ui login-header">
            <div class="ui grid">
                <div class="row header-row1"></div>
                <div class="row text-center">
                    <h1 class="ui header white" style="margin-left:30px">
                        <i class="codepen icon"></i>
                        用户登录
                    </h1>
                </div>
            </div>
        </div>

        <div class="ui three column stackable grid login-div">
            <div class="column"></div>
            <div class="column">
                <form id="login" class="ui fluid form segment">
                    <div class="field">
                        <div id="message" style="color:red"></div>
                    </div>
                    <div class="field">
                        <label class="">用户名</label>
                        <div class="ui left icon input">
                            <input id="username" type="text" name="userName" placeholder="">
                            <i class="user icon"></i>
                            <div class="ui corner label">
                                <i class="icon asterisk"></i>
                            </div>
                        </div>
                    </div>
                    <div class="field">
                        <label class="">密码</label>
                        <div class="ui left icon input">			
                            <input id="password" type="password" name="password" placeholder="">
                            <i class="lock icon"></i>
                            <div class="ui corner label">
                                <i class="icon asterisk"></i>
                            </div>
                        </div>
                    </div>
                    <div class="inline field" style="">
                        <div class="ui checkbox">
                            <input type="checkbox" name="terms">
                            <label>记住密码</label>
                        </div>
                    </div>
                    <div class="inline field" style="text-align:right">
                        <div id="submit" class="ui blue submit button">登录</div>
                    </div>
                </form>
            </div>
            <div class="column"></div>
        </div>
    </body>
</html>