
<style type="text/css">
	#makeLoans-m-flex .u-tab td{padding: 5px;min-width: 130px;max-width: 130px;word-break: break-all;}
	#makeLoans-m-flex td{
		border: 1px solid #869098;
	}
	#makeLoans-m-flex table{
		border-collapse:collapse;
	    border-spacing:0;
	    margin:0;
	    padding:0;
	    border:none;
	}
	#makeLoans-m-flex tr:hover td:first-child{
		color: blue;
	}
</style>
<section id="makeLoans-m-flex" class="m-flex">  
</section>  
<script type="text/javascript" src="/js/makeLoans.js"></script>
<script type="text/javascript" src="js/calendar.js"></script>