<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>鹰眼系统 登录</title>
        <link rel="shortcut icon" type="image/x-icon" href="image/logo.ico"/>
        <link rel="stylesheet" type="text/css" href="/css/login.css"/>
    </head>
    <body>
	    <img src="image/loginBG.jpg" width="100%" height="100%" class="img"/>
	    <div class="login_box Auto">
	        <div class="logo"><img src="/image/login.jpg" width="20%" style="border-radius: 50%";></div>
	        <div id="error_box" style="color: red;"></div>
	        <form class="form">
		        <input  type="text" name="" id="uname" value="" placeholder="用户名"  class="input"/>
		        <input type="password" name="" id="upass" value="" placeholder="密码" class="input" style="border: none;"/>
			</form>
		    <input type="button" value="登录" onclick="fnLogin()" class="button pointer"/> 
	    </div>
	<script src="/js/jquery.min.js" type="text/javascript"></script>
	<script src="/js/jquery.cookie.js" type="text/javascript"></script>
	<script src="/js/resolution.js" type="text/javascript"></script>
	<script type="text/javascript">
	$(document).keyup(function(event){
		  if(event.keyCode ==13){
		    fnLogin();
		  }
	});
	$('input').blur(function(){
		fnLogin();
	})
function fnLogin() {
    var oUname = document.getElementById("uname");
    var oUpass = document.getElementById("upass");
    var oError = document.getElementById("error_box");
    var isNotError = true;
    if (oUname.value.length > 20 || oUname.value.length < 2) {
    	//oUname.select();
        oError.innerHTML = "*用户名长度必须在2~20位之间";
        isNotError = false;        
        return ;

    } else if (oUname.value.charCodeAt(0) >= 48 && oUname.value.charCodeAt(0) <= 57) {
    	//oUname.select();
        oError.innerHTML = "*用户名开头不能为数字";
        isNotError = false;
        return;
    } else {
        for (var i = 0; i < oUname.value.length; i++) {
            if ((oUname.value.charCodeAt(i) > 122 || oUname.value.charCodeAt(i) < 97) && (oUname.value.charCodeAt(i) > 57 || oUname.value.charCodeAt(i) < 48)) {
                //oUname.select();
                oError.innerHTML = "*用户名只能包含小写字母和数字";
                isNotError = false;
                return;
            }
        }
    }
    if (oUpass.value.length > 20 || oUpass.value.length < 2) {
    	//oUpass.select();
        oError.innerHTML = "*密码长度必须在2~20位之间";
        isNotError = false;
        return;
    }
	
    $.ajax({
        url: "/login/doLogin",
        async: true,
        type: 'POST',
        data: {name: oUname.value, pass: oUpass.value},
        success: function (text, textStatus) {
            var o = jQuery.parseJSON(text);
            if (o.c === 0) {
            	$.cookie("userName",$('#uname').val(),{
            		expires: 365
            	});
//          	var url = "http://us.xiwanglife.com/userservice/login.do?userName="+oUname.value+"&password="+oUpass.value;
//          	$("body").append("<iframe id='loginI' src='"+url+"'>");
/*
 新加功能（待完成）
 *  1. 当前账号是否具备权限
 *  2. 定时发送请求
 * 
 * */
            	$.ajax({
			        url: "http://us.xiwanglife.com/userservice/login.do?",
			        async: false,
			        type: 'POST',
			        data: {
			        	userName: oUname.value, password: oUpass.value
			        },
			        success:function(data){
			        	console.log(data);
			        	$.cookie("US_SESSION_ID", data.sessionId, { domain: '.xiwanglife.com' });
			        }
			    });
          	//alert(1);
                window.location.href = o.t;
            } else if (o.c === -1) {
                oError.innerHTML = o.t;
            }
        }
    });
}
</script>
    </body>
</html>
