<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=9">
        <title>恒大金服实时报表系统</title>

        <link rel="stylesheet" type="text/css" href="/js/semantic/semantic.min.css">
        <script type="text/javascript" src="/js/jquery.min.js"></script>
        <script src="/js/semantic/semantic.min.js"></script>

        <style>
            body {
                font-family: Verdana,Arial,Helvetica,sans-serif;
                margin: 0;
                background-color:#35b5d3;
                text-align: center;
                overflow: hidden;
                
            }
            .title{
                text-align: center;
                width: 100%;
                height: 100px;
                font-size: 60px;
                margin-top: 30px;
                line-height: 100px;
/*                background-color: #208193;*/
                color: #fff;
            }
            .ui.grid{
                margin:0;
            }
            .login-header {
                background-color: #0066b1;
            }

            .ui.white {
                color: #fff;
            }
            .text-center{
                text-align:center;
            }

            .ui.login-div{
                width:70%;
                margin:0 auto;
                padding:30px 50px;
                border-radius:15px;
                background-color: #fff
            }

            #login-form{
            }

            form div{
                margin-bottom: 15px;
            }

            .myinput{
                
            }
            input.myinput{
                
            }
            
            input::-webkit-input-placeholder{
                
            }
/*
            .myinput i{
                font-size: 40px;
                display: inline-block
            }*/
        </style>
        <script>

            $(document).ready(function () {
                
                var w = $(window).width();
                var h = $(window).height();

                var topHeight = (h - $(".login-div").height() - 60)/2 - 50;
                var titleTopHeight = (topHeight - 100)*0.2;
                //alert($(".login-div").height());
                $("#top").height(topHeight);
                $(".title-top").height(titleTopHeight);
                $("#submit").click(function () {
                    var name = $("#username").val();
                    var pass = $("#password").val();
                    $.ajax({
                        url: "/login/doLogin",
                        async: true,
                        type: 'POST',
                        data: {name: name, pass: pass},
                        success: function (text, textStatus) {
                            var o = jQuery.parseJSON(text);
                            if (o.c === 0) {
                                window.location.href = o.t;
                            } else if (o.c === -1) {
                                $("#message").text(o.t);
                            }
                        }
                    });
                });
            });

        </script>

    </head>
    <body>
        <div id="top">
            <div class="title-top"></div>
            <div class="title">
                恒大金服实时报表系统
            </div>
        </div>
        <div class="ui login-div stackable">
            <form id="login-form" class="ui fluid form">
                <div class="field">
                    <div id="message" style="color:red"></div>
                </div>
                <div class="field">
                    <div class="ui left icon input massive">
                        <input id="username" style="border: 2px solid #aaa" type="text" name="userName" placeholder="">
                        <i class="user icon"></i>
                    </div>
                </div>
                <div class="field">
                    <div class="ui left icon input massive">			
                        <input id="password" style="border: 2px solid #aaa" type="password" name="password" placeholder="">
                        <i class="lock icon"></i>
                    </div>
                </div>
                <div class=" field">
                    <div class="ui left massive">
                        <div id="submit" style="height:90px;font-size:40px;line-height:30px" class="ui fluid blue submit button">登录</div>
                    </div>
                </div>
            </form>
        </div>
    </body>
</html>