<style type="text/css">
	h2{line-height:30px; font-size:20px;}
	h3{margin:10px 0;}
	a,a:hover{ text-decoration:none;}
	pre{font-family:'微软雅黑'}
	.box{width:970px; padding:10px 20px; background-color:#fff; margin:10px auto;}
	.box a{padding-right:20px;}
	.demo1,.demo2,.demo3,.demo4,.demo5,.demo6{margin:25px 0;}	
	.layinput{height: 22px;line-height: 22px;width: 150px;margin: 0;}
    .pre-sql{float:left;font-size:30px;line-height:35px;color:#F2F6FB;width:200px !important;height:40px}
    .pre-sql:hover{color:#F2F6FB;cursor: pointer}
    .pre-sql:active{color:#F2F6FB;cursor: pointer}
    #pre-sql1{position: absolute;right: 30vw;top:10px;text-align:center;}
    #zclip-ZeroClipboardMovie_1{width:200px !important;}
    #ZeroClipboardMovie_1{width:200px !important;}
</style>
<div class="section clearfix">
    <div class="g-menu in_left">
        <ul class="mylable clearfix">
            <li class="in_left mylable01 mylableBorder"><a href="#">标签</a></li>
            <li class="in_right mylable02 "onclick="promptShow()"><a href="#">我的标签</a></li>
        </ul>  
        <div id="left">
            <div id="menu"></div>
        </div>
    </div>
    <!--==========i========================以上是左盒子===========================================-->
    <div class="g-lable in_left ">
            <div class="editor clearfix">
                <form class="form1">
                    <input type="text" placeholder="输入活动名称或描述" class="inp1 in_left" id="prom_name"/>                            			               
                </form>
                <div class="addlable">
                    <div id="pre-sql1" class="pre-sql">HQL</div>
                    <p id="add_TabGroups">+添加标签组</p>
                </div>
            </div>
            <div class="lablegroups">
                <div id="right">

                </div>
            </div>
            <p class="addline"><i class="pointer2 mouseHover more" onclick="more()">更多</i></p>
            <!--以上是添加标签组的部分-->      
            <div class="time"style="position: relative;">  
        	 	<div class="form2"> 
                	<section class="slide_Up"> 
                        <div id="DATE"class="u-item  u-date">
                            <input type="text" id="startDate" class="pointer queryStartDate1" placeholder="选择活动开始日期" />
                            <!--<div id="dd" style="padding-bottom: 20px;" class="d2"></div>-->
                        </div>
                        <div class="u-item  u-nameActivity">
                            <input type="text" id="except_proms" class="record pointer" placeholder="排除活动名单" onclick="recordSelect(this),recordChange(this)" onchange="recordChange(this)"/>
                            <input type="hidden" id="hide_except_proms" class="record pointer" />
                            <b>排除</b>
                            <div class="select_box u-record">
                            	<section class="history_content">
	                            	<p><i>ID</i><i>活动名</i><i>创建人</i></p>
	                                <ul class="select slideUp"id="slideUp"></ul>
	                                <div class="submit_btn pointer2" onclick="historySelect(this)">确定</div>
                            	</section>
                            </div>
                        </div>
                        <div class="u-item">
                        	<input type="text" id="include_proms" class="record pointer" placeholder="包含活动名单" onclick="recordSelect(this),recordChange(this)" onchange="recordChange(this)" />
                            <input type="hidden" id="hide_include_proms" class="record pointer" />
                            <b>包含</b>
                            <div class="select_box u-record">
                            	<section class="history_content">
	                            	<p><i>ID</i><i>活动名</i><i>创建人</i></p>
	                                <ul class="select slideUp"id="slideUp2"></ul>
	                                <div class="submit_btn pointer2" onclick="historySelect(this)">确定</div>
                            	</section>
                            </div>
                        </div>
                	</section>
                	<div class="btn">       
                        <button id="submit-prom" value="提交" class="time_btn">提交</button>
                    </div>
                </div>  	
            </div>        
            <!--以上是日历的效果 <-->
        </div>
    
</div>
<script type="text/javascript">
	(function($){
		moduleLableSize();
	})(jQuery)
	$('.queryStartDate1').fdatepicker({
		format: 'yyyy-mm-dd hh:ii:ss',
		pickTime: true
	});
	
	
    var d2 = [];
    var formatSql1,excepts,includes,dataStyle=false;
    $(function () {
        getTablelist();
       	mouseenterTip();
        state();
        statusInput();
        // 复制
        $("#pre-sql1").click(function(){
	   		var r = makeSql();
            formatSql1 = $.format(r[0],{method: 'sql'});
            $.dialog({
                title: '',
                content: "<pre class='brush:sql;'>"+formatSql1+"</pre>",
                columnClass: 'col-md-1',
                animation: 'top',
                closeAnimation: 'bottom'
            });
            SyntaxHighlighter.highlight();
        });
    });
    $(window).resize(moduleLableSize)
//----------------------------------------  function  ------------------------------
	//  初始化标签数据   
	function getTablelist() {   
	    // 是否是复制功能跳转
	    if (copyId != undefined) {
	    	$.ajax({
	                url: "/get/onePromsHistory",
	                async: true,
	                type: 'POST',
	                data:{
	                	id:copyId
	                },
	                success: function (text, status) {
						var data = JSON.parse(text);
						console.log(data)
						d2 = eval(data.tags);
						createModels(d2)
						
						includes= data.includes;
				        $('#prom_name').val(data.name);
				        $('#except_proms').val(excepts);
				        $('#include_proms').val(includes);
				        if($('#except_proms').val().length>0 || $('#include_proms').val().length>0){
				        	$('.slide_Up').css('overflow','inherit').stop().animate({'height':'70px','opacity':1},500);
				        }
				        dataStyle = true;
	                }
	                
	           });
		}
		getAsideNav();
		
	}

	function getAsideNav() {
	    $.ajax({
	        url: "/get/promsHistoryLimit",
	        async: true,
	        type: 'get',                                    
	        success: function (text, textStatus) {
	            var msg = jQuery.parseJSON(text);
	            for (var i = 0; i < msg.length; i++) {     
	        		var html='<li><i>'+msg[i].id + '</i><i>'+msg[i].name+'</i><i>'+msg[i].submitter+'</i></li>';      
	           		$('#slideUp').append(html);
	           		$('#slideUp2').append(html);
	            }
	            if(dataStyle){
	            	matching(excepts,'1');
					matching(includes,'2');
	            }else{
	            	createModels(d2)
	            }
				
	        }
	    });
	}
	
	// 筛选活动中 用于向后台传递值的隐藏 input 元素的 val() ;
	function matching(data,index){
		var arr={};
		var b = $('.slide_Up').children().eq(index).find('li');
		if(!data || data < 1)return
		data = data.split(',');
		for(var i = data.length-1 ; i >= 0 ; i--){
			for(var n = b.length-1 ; n >= 0 ; n--){
				if(data[i] == $(b).eq(n).children(':first').html()){
					arr[data[i]]=$(b).eq(n).children(':last').html();
				}
			}
		}
		$('.slide_Up').children('.u-item').eq(index).children('input:last').val(JSON.stringify(arr));
	}
	
	function moduleLableSize(){
	 	$('.g-lable').css('width',$('.section').width()-$('.g-menu').outerWidth()-2);
	} 

// 状态集合
function state(){
	$('.group-wrapper').css("height", $('.group-wrapper').children('.group').height() + 20);      
    //  历史记录 选中 & 不选
    $('.select_box').delegate('li','click',function () {
    	$(this).attr('class') == undefined ? $(this).attr('class','slideLi') : $(this).removeClass();
    })
    //  双击标签按钮 收起菜单栏
    $('.mylableBorder').dblclick(function () {
        $('#menu').children('ul').find('ul').slideUp(300);
    })
     // 阻止冒泡
    $('.u-record').click(function(event){
    	event.stopPropagation();
    })
}

// 历史记录 show & hide;
function recordSelect(e){
	$('.slide_Up .u-record,.slide_Up #dd').hide();
	if($(e).siblings('.u-record').is(':hidden')){
		$(e).siblings('.u-record').show();
	}else{
		$(e).siblings('.u-record').hide();
	}
	$(document).one('click',function(){
		$(e).siblings('.u-record').hide();
		var events=$(e).siblings('.u-record').find('.submit_btn');
		historySelect(events)
	})
	event.stopPropagation();
}
// 显示选中记录
function historySelect(e){
	var group={}; // 选中项目 id && 创建人
	var itemID=[];
	var initialHtml=$(e).parents('.u-record').siblings('input').attr('placeholder');
	var list=$(e).parents('.u-record').find('.slideLi');
    $(e).parents('.u-record').hide();        
    if (list.length> 0) {
    	for(var i=0;i<list.length;i++){
    		group[$(list).eq(i).children('i:first').html()]=$(list).eq(i).children('i:last').html();
    		itemID.push($(list).eq(i).children('i:first').html());
    	}
    	$(e).parents('.u-item').children('input:first').val(itemID);
    	$(e).parents('.u-item').children('input:last').val(JSON.stringify(group));
    } else {
        $(e).parents('.u-record').siblings('input').val('').attr('placeholder', initialHtml);
    }
} 
// 多值选中
function recordChange(e){
	var arr=$(e).val();
	var list=$(e).parents('.u-item').find('li');
	arr=arr.split(',');
	for(var i=0;i<arr.length;i++){
		for(var n=0;n<list.length;n++){
			if(arr[i] == $(list).eq(n).children(':first').html()){
				$(list).eq(n).addClass('slideLi');
			}
		}
	}
}
// 多值提示
function statusInput(){
	$('.slide_Up b').each(function(){
		var count_top=$(this).prev('input').outerHeight()-$(this).height()/2-1.5;
		$(this).css({'top':count_top});
	})
}
// 显示隐藏日期选择框
function more() {
	e=$('.slide_Up');
	if(e.css('opacity') == 0){
		e.css('overflow','inherit').stop().animate({'height':'70px','opacity':1},500);
	} else{
		e.css('overflow','hidden').stop().animate({'height':0,'opacity':0},500);  
	}
} 
// tips   
function mouseenterTip() {	
    var div = $("<div id='tip'></div>");
    div.appendTo("body");
    div.hide();
    //给所有a标签绑定三个事件
    $("#menu").delegate('a','mouseenter',function () {
    		
        var List = $(this).html();
        if (List.length > 10) {
            //鼠标移入：将title值添加到提示框中并显示
            var t = $(this).html();
            $("#tip").html(t).stop().fadeIn(500);
        } else {
            false;
        }
    }).delegate('a','mouseleave',function () {
        //鼠标移除：让提示框隐藏
        $("#tip").stop().fadeOut(300);
    }).delegate('a','mousemove',function (e) {
        //鼠标移动：获取鼠标坐标.
        //提示框随着鼠标的移动而移动,增加一点偏移
        $("#tip").css({
            left: e.pageX + 10,
            top: e.pageY + 10
        })
    })
}
</script>
<script src="/js/addtags.js" type="text/javascript"></script>