<section class="logContent">
	<div class="logContent-tbody">
		<table id="logInformation-tab">
			<tr><td style="width: 134px;">任务名称</td><td id="taskName">loading...</td></tr>
			<tr><td>参数信息</td><td id="params">loading...</td></tr>
			<tr><td>备注说明</td><td id="remark">loading...</td></tr>
			<tr><td>任务状态</td><td id="status">loading...</td></tr>
			<tr><td>日志路径</td><td id="logPath">loading...</td></tr>
			<tr><td>日志路径</td><td id="errorLogPath">loading...</td></tr>
			<tr><td>日志信息</td><td id="content" style="line-height: 150%;">loading...</td></tr>
		</table>
	</div>
</section>