<div class="content_table">
	<ul class="clearfix bottom"style="margin-bottom: 10px;position: relative;padding-top: 10px;">
    	<li class="fl  markup tab Pointer">交易人数</li>
        <li class="fr mright_ma"style="position: absolute;">数据刷新日期：</li>
    </ul>
    <!--  分析图表 start -->
  	<!-- 为ECharts准备一个具备大小（宽高）的Dom -->
	<div id="main" style="width:100%;height:300px;"></div>
	<!--  分析图表 end-->
</div>

<script type="text/javascript" src="/js/echarts.min.js"></script>
<script type="text/javascript">
	$(function(){
		getPeopleWarning();
	});
function getPeopleWarning(){	
	var objAction={
		id:34,
		market_channel:ChannelName
	};
	objAction=JSON.stringify(objAction);
	$.ajax({
		type:"get",
		url:"/get/mysqlData",
		data:{
			j:objAction
		},
		beforeSend:function (){
        	$('.loading').show();
        },
		success: function (meg) {      	
            meg=JSON.parse(meg);
			var  objMsg = meg.details.sigfactor.values;
			initChart(meg.details.plot_data.values);			
			var e="数据刷新日期："+meg.details.update_date.values[0].update_date;
			$('.mright_ma').html(e);
			// TH 日期 
			Dates(meg.details.update_date.values[0].update_date,$('#people_tables'));
			setTimeout(function(){$('.loading').hide()},1500);
		}
	});
}
function  initChart(obj){
	var mr=new Array(),mt=new Array(),_mDate=new Array();
	for(var i=0;i<obj.length;i++){
		mr.push(obj[i].trans_amount);		
		_mDate.push(obj[i].trans_date);
		//  筛选过滤掉 预警值为 0  的值
		if(i==0 && obj[i].mv_trans_amount==0){
			mt.push("");
		}else{
			if(obj[i].mv_trans_amount==0 && obj[i-1].mv_trans_amount==0){
				mt.push("");
			}else{
				mt.push(obj[i].mv_trans_amount);
			}
		}				
	}
    	var myChart = echarts.init(document.getElementById('main'));
    // 指定图表的配置项和数据
    
    var option = {
	    title: {
	        text: ''
	    },
	    tooltip : {
	        trigger: 'axis'
	    },
	    legend: {
	        data:['注册人数','长期趋势']
	    },
	    toolbox: {
	        feature: {
	            saveAsImage: {}
	        }
	    },
	    grid: {
	    	top:'15%',
	        left: '1%',
	        right: '3%',
	        bottom: '3%',
	        containLabel: true
	    },
	    xAxis : [
	        {
	            type : 'category',
	            boundaryGap : false,
	            data : _mDate
	        }
	    ],
	    yAxis : [
	        {
	            type : 'value'
	        }
	    ],
	    series : [
	        {
	            name:'注册人数',
	            type:'line',
	            areaStyle: {"background-color":"rgba(0,0,0,0)"},
	            data:mr
	        },
	        {
	            name:'长期趋势',
	            type:'line',
	            areaStyle: {"background-color":"rgba(0,0,0,0)"},
	            data:mt
	        }
	    ]};

    // 使用刚指定的配置项和数据显示图表。
    myChart.setOption(option);
}
</script>
