<!-- start content table -->
<div class="content_table g-table" style="overflow-y: hidden !important;">
    <!--  start table header  -->		    
	<div class="table-head">
        <table style="border: none;">
            <colgroup><col/><col /><col /><col /><col /><col /><col /><col /><col /><col /><col /><col /><col /><col /><col /><col /></colgroup>
            <thead>
                <tr>
                	<th>
                		<span sortName="market_channel"><i>渠道号</i></span>
                	</th>
                	<th>
                		<span sortName="create_days"><i>注册天数</i></span>
                		<div class="sort_item">
                			<a href="javascript:;"class="sort positiveSequence" onclick="positiveSequence(this)"><img src="/image/ff_03.png" class="arrow1"/></a>
                			<a href="javascript:;"class="sort Reverse_order" onclick="Reverse_order(this)"><img src="/image/0_03.png" class="arrow1"/></a>
                		</div>
                	</th>
                	<th>
                		<span sortName="reg_cnt"><i>注册人数</i></span>
                		<div class="sort_item">
                			<a href="javascript:;"class="sort positiveSequence" onclick="positiveSequence(this)"><img src="/image/ff_03.png" class="arrow1"/></a>
                			<a href="javascript:;"class="sort Reverse_order" onclick="Reverse_order(this)"><img src="/image/0_03.png" class="arrow1"/></a>
                		</div>
                	</th>
                	<th>
                		<span sortName="cert_cnt"><i>实名人数</i></span>
                		<div class="sort_item">
                			<a href="javascript:;"class="sort positiveSequence" onclick="positiveSequence(this)"><img src="/image/ff_03.png" class="arrow1"/></a>
                			<a href="javascript:;"class="sort Reverse_order" onclick="Reverse_order(this)"><img src="/image/0_03.png" class="arrow1"/></a>
                		</div>
                	</th>
                	<th>
                		<span sortName="card_cnt"><i>绑卡人数</i></span>
                		<div class="sort_item">
                			<a href="javascript:;"class="sort positiveSequence" onclick="positiveSequence(this)"><img src="/image/ff_03.png" class="arrow1"/></a>
                			<a href="javascript:;"class="sort Reverse_order" onclick="Reverse_order(this)"><img src="/image/0_03.png" class="arrow1"/></a>
                		</div>
                	</th>
                	<th>
                		<span sortName="trans_cnt"><i>交易人数</i></span>
                		<div class="sort_item">
                			<a href="javascript:;"class="sort positiveSequence" onclick="positiveSequence(this)"><img src="/image/ff_03.png" class="arrow1"/></a>
                			<a href="javascript:;"class="sort Reverse_order" onclick="Reverse_order(this)"><img src="/image/0_03.png" class="arrow1"/></a>
                		</div>
                	</th>
                	<th>
                		<span sortName="reg_cert_rate"><i>注册实名率</i></span>
                		<div class="sort_item">
                			<a href="javascript:;"class="sort positiveSequence" onclick="positiveSequence(this)"><img src="/image/ff_03.png" class="arrow1"/></a>
                			<a href="javascript:;"class="sort Reverse_order" onclick="Reverse_order(this)"><img src="/image/0_03.png" class="arrow1"/></a>
                		</div>
                	</th>
                	<th>
                		<span sortName="cert_card_rate"><i>实名绑卡率</i></span>
                		<div class="sort_item">
                			<a href="javascript:;"class="sort positiveSequence" onclick="positiveSequence(this)"><img src="/image/ff_03.png" class="arrow1"/></a>
                			<a href="javascript:;"class="sort Reverse_order" onclick="Reverse_order(this)"><img src="/image/0_03.png" class="arrow1"/></a>
                		</div>
                	</th>
                	<th>
                		<span sortName="card_trans_rate"><i>绑卡交易率</i></span>
                		<div class="sort_item">
                			<a href="javascript:;"class="sort positiveSequence" onclick="positiveSequence(this)"><img src="/image/ff_03.png" class="arrow1"/></a>
                			<a href="javascript:;"class="sort Reverse_order" onclick="Reverse_order(this)"><img src="/image/0_03.png" class="arrow1"/></a>
                		</div>
                	</th>
                	<th>
                		<span sortName="reg_trans_rate"><i>注册交易率</i></span>
                		<div class="sort_item">
                			<a href="javascript:;"class="sort positiveSequence" onclick="positiveSequence(this)"><img src="/image/ff_03.png" class="arrow1"/></a>
                			<a href="javascript:;"class="sort Reverse_order" onclick="Reverse_order(this)"><img src="/image/0_03.png" class="arrow1"/></a>
                		</div>
                	</th>
                	<th>
                		<span sortName="coupon_use_type_cash_cnt"><i>现金券用劵数</i></span>
                		<div class="sort_item">
                			<a href="javascript:;"class="sort positiveSequence" onclick="positiveSequence(this)"><img src="/image/ff_03.png" class="arrow1"/></a>
                			<a href="javascript:;"class="sort Reverse_order" onclick="Reverse_order(this)"><img src="/image/0_03.png" class="arrow1"/></a>
                		</div>
                	</th>
                	<th>
                		<span sortName="coupon_use_type_add_rate_cnt"><i>加息劵用劵数</i></span>
                		<div class="sort_item">
                			<a href="javascript:;"class="sort positiveSequence" onclick="positiveSequence(this)"><img src="/image/ff_03.png" class="arrow1"/></a>
                			<a href="javascript:;"class="sort Reverse_order" onclick="Reverse_order(this)"><img src="/image/0_03.png" class="arrow1"/></a>
                		</div>
                	</th>
                	<th>
                		<span sortName="coupon_use_type_newcus_cnt"><i>新手劵用劵数</i></span>
                		<div class="sort_item">
                			<a href="javascript:;"class="sort positiveSequence" onclick="positiveSequence(this)"><img src="/image/ff_03.png" class="arrow1"/></a>
                			<a href="javascript:;"class="sort Reverse_order" onclick="Reverse_order(this)"><img src="/image/0_03.png" class="arrow1"/></a>
                		</div>
                	</th>
                	<th>
                		<span sortName="trans_order_cnt"><i>交易订单数</i></span>
                		<div class="sort_item">
                			<a href="javascript:;"class="sort positiveSequence" onclick="positiveSequence(this)"><img src="/image/ff_03.png" class="arrow1"/></a>
                			<a href="javascript:;"class="sort Reverse_order" onclick="Reverse_order(this)"><img src="/image/0_03.png" class="arrow1"/></a>
                		</div>
                	</th>
                	<th>
                		<span sortName="trans_amt"><i>交易金额</i></span>
                		<div class="sort_item">
                			<a href="javascript:;"class="sort positiveSequence" onclick="positiveSequence(this)"><img src="/image/ff_03.png" class="arrow1"/></a>
                			<a href="javascript:;"class="sort Reverse_order" onclick="Reverse_order(this)"><img src="/image/0_03.png" class="arrow1"/></a>
                		</div>
                	</th>	
                	<th>
                		<span sortName="clus_label"><i>分类标签</i></span>
                		<div class="sort_item">
                			<a href="javascript:;"class="sort positiveSequence" onclick="positiveSequence(this)"><img src="/image/ff_03.png" class="arrow1"/></a>
                			<a href="javascript:;"class="sort Reverse_order" onclick="Reverse_order(this)"><img src="/image/0_03.png" class="arrow1"/></a>
                		</div>
                	</th>
                </tr>
            </thead>
        </table>
	</div>
	<!--  end table header  -->
	<!--  start table section  -->
    <div class="table-body">
     	<table id="classification_tables" style="border: none;">
           	<colgroup><col /><col /><col /><col /><col /><col /><col /><col /><col /><col /><col /><col /><col /><col /><col /><col /></colgroup>
            <tbody>
            </tbody>
   		</table>
	</div>	   		
	<!--  end table section  -->
</div>
<!-- end content table -->
	<!--<script src="/js/loadTableSize.js" type="text/javascript"></script>-->
	<script type="text/javascript">	
	var msgSort;
		$(function(){
			getModel1();
			//document.location = 	'http://localhost:8081/index.phtml#trait_detail'	
		})
		function getModel1(){
			//$('#classification_tables tbody').remove();
			var objAction={
				id:40,
				clus_label:Channel_classification
			};
			objAction=JSON.stringify(objAction);
			$.ajax({
					url:"/get/mysqlData",
					type:"get",			
					data:{
						j:objAction
					},
					beforeSend:function (){
			        	$('.loading').show();
			        },
					success: function (meg) {  	
			            meg=JSON.parse(meg);
						var objMsg=meg.details.homepage.values;
						$('.number_number').html(number_number);
						msgSort=objMsg;
						for(var i=0;i<objMsg.length;i++){																						        
							var html='<tr><td><i class="mouseHover pointer activityName sizeWidth">'+
								objMsg[i].market_channel+'</i></td>'+	
								'<td><span>'+objMsg[i].create_days+'</span></td>'+
								'<td><span>'+objMsg[i].reg_cnt+'</span></td>'+
								'<td><span>'+objMsg[i].cert_cnt+'</span></td>'+
								'<td><span>'+objMsg[i].card_cnt+'</span></td>'+
								'<td><span>'+objMsg[i].trans_cnt+'</span></td>'+
								'<td><span>'+objMsg[i].reg_cert_rate+'</span></td>'+
								'<td><span>'+objMsg[i].cert_card_rate+'</span></td>'+
								'<td><span>'+objMsg[i].card_trans_rate+'</span></td>'+
								'<td><span>'+objMsg[i].reg_trans_rate+'</span></td>'+
								'<td><span>'+objMsg[i].coupon_use_type_cash_cnt+'</span></td>'+
								'<td><span>'+objMsg[i].coupon_use_type_add_rate_cnt+'</span></td>'+
								'<td><span>'+objMsg[i].coupon_use_type_newcus_cnt+'</span></td>'+
								'<td><span>'+objMsg[i].trans_order_cnt+'</span></td>'+
								'<td><span>'+objMsg[i].trans_amt+'</span></td>'+
								'<td><span>'+objMsg[i].clus_label+'</span></td></tr>'		
						$(html).appendTo('#classification_tables');
					}
					onloadings('#trait_detail');
					setTimeout(function(){$('.loading').hide()},1500);					
				}			
			})
			
		}
		// sort
		function positiveSequence(e){
			var title=$(e).parents('th').children('span').attr('sortName');
			$('#classification_tables tbody').remove();	
			function Sort(a,b){
				return a[title] - b[title];					
			}	
			msgSort.sort(Sort);				
			for(var i=0;i<msgSort.length;i++){																						        
				var html='<tr><td><i class="mouseHover pointer activityName sizeWidth">'+
					msgSort[i].market_channel+'</i></td>'+	
					'<td><span>'+msgSort[i].create_days+'</span></td>'+
					'<td><span>'+msgSort[i].reg_cnt+'</span></td>'+
					'<td><span>'+msgSort[i].cert_cnt+'</span></td>'+
					'<td><span>'+msgSort[i].card_cnt+'</span></td>'+
					'<td><span>'+msgSort[i].trans_cnt+'</span></td>'+
					'<td><span>'+msgSort[i].reg_cert_rate+'</span></td>'+
					'<td><span>'+msgSort[i].cert_card_rate+'</span></td>'+
					'<td><span>'+msgSort[i].card_trans_rate+'</span></td>'+
					'<td><span>'+msgSort[i].reg_trans_rate+'</span></td>'+
					'<td><span>'+msgSort[i].coupon_use_type_cash_cnt+'</span></td>'+
					'<td><span>'+msgSort[i].coupon_use_type_add_rate_cnt+'</span></td>'+
					'<td><span>'+msgSort[i].coupon_use_type_newcus_cnt+'</span></td>'+
					'<td><span>'+msgSort[i].trans_order_cnt+'</span></td>'+
					'<td><span>'+msgSort[i].trans_amt+'</span></td>'+
					'<td><span>'+msgSort[i].clus_label+'</span></td></tr>'		
				$(html).appendTo('#classification_tables');		
			}
			onloadings('#trait_detail');				
		}				
		
		//  动态获取表格 宽高 值；								
		function onloadings(e){
			var bodyH=$('body').height();                   	// body height
			var headH=$('.container_header').outerHeight(); 			// header-top  height
			var tableH=$(e).find('.table-head table').outerHeight(); // table head height
            var containerH=bodyH-headH;							// container height
			var thList=$(e).find('.table-head tr').eq(0).find('th');// tr(th) length
			var trW=0;											//tr width
			//超长名字专用	
			var iWidth=($(e).find('.sizeWidth').parent('td').width()-10)/100;		
			var table_bodyH=(containerH-tableH); 				//table_body height	
			// 循环获取th总宽度
			for(var i=0;i<thList.length;i++){
				trW=trW+$(thList).eq(i).outerWidth();				// TH 盒模型宽度;
			}
			$('.container').css('height',bodyH - headH);
			// tbody width size	
			$(e).children('.content_table').css('width',trW);
			$(e).find('.table-body').css({height:$(e).height() - tableH});
			$(e).find('.sizeWidth').css("width",iWidth+'px');
                        $(e).find('tr').css('width',trW);
		}	
		function Reverse_order(e){
			var title=$(e).parents('th').children('span').attr('sortName');
			$('#classification_tables tbody').remove();	
			function Sort(a,b){
				return b[title] - a[title];					
			}	
			msgSort.sort(Sort);				
			for(var i=0;i<msgSort.length;i++){																						        
				var html='<tr><td><i class="mouseHover pointer activityName sizeWidth">'+
					msgSort[i].market_channel+'</i></td>'+	
					'<td><span>'+msgSort[i].create_days+'</span></td>'+
					'<td><span>'+msgSort[i].reg_cnt+'</span></td>'+
					'<td><span>'+msgSort[i].cert_cnt+'</span></td>'+
					'<td><span>'+msgSort[i].card_cnt+'</span></td>'+
					'<td><span>'+msgSort[i].trans_cnt+'</span></td>'+
					'<td><span>'+msgSort[i].reg_cert_rate+'</span></td>'+
					'<td><span>'+msgSort[i].cert_card_rate+'</span></td>'+
					'<td><span>'+msgSort[i].card_trans_rate+'</span></td>'+
					'<td><span>'+msgSort[i].reg_trans_rate+'</span></td>'+
					'<td><span>'+msgSort[i].coupon_use_type_cash_cnt+'</span></td>'+
					'<td><span>'+msgSort[i].coupon_use_type_add_rate_cnt+'</span></td>'+
					'<td><span>'+msgSort[i].coupon_use_type_newcus_cnt+'</span></td>'+
					'<td><span>'+msgSort[i].trans_order_cnt+'</span></td>'+
					'<td><span>'+msgSort[i].trans_amt+'</span></td>'+
					'<td><span>'+msgSort[i].clus_label+'</span></td></tr>'		
				$(html).appendTo('#classification_tables');		
			}
			onloadings('#trait_detail');
		}
		
		$(window).resize(function(){onloadings('#trait_detail');})
	</script>
</html>
