<!DOCTYPE html>
<html>  
    <head>
        <title>Hello World</title>  

    </head>  
    <body>  
        <input type="button" value="AAAAA" onclick="aclick()"/>
    </body> 
    <script>
        function aclick() {
            window.setTimeout(function(){
                console.debug(1);
            }, 0);
            
        }
        window.setTimeout(function () {
            //window.setInterval(function(){}, 100);
            while (true) {
                
            }
        }, 1000);

    </script> 
</html>  