<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />

        <!-- Site Properties -->
        <title>HCharts</title>

        <link rel="stylesheet" type="text/css" href="/js/jquery-ui.min.css">

        <script src="/js/jquery.min.js"></script>
        <script src="/js/d3.v4.js"></script>
        <script src="/js/jquery-ui.min.js"></script>



        <style>
            body{margin:0}
            .axis line,.axis path{fill:none;stroke:black;shape-rendering:crispEdges;stroke-width: 2px;}
            .axis text {
                font-family: sans-serif;
                font-size: 13px;
                text-anchor: left;
                fill:black;
                word-break:break-all
            }
            .line {fill:none;stroke:red;stroke-width: 3px;}

        </style>
        <script>
            var svg;
            var domains;
            var gAxis;
            var MX = 0;
            var parseTime = d3.timeParse("%Y-%m-%d %H:%M:%S");
            var data = [
                {date: new Date("2016-06-20 00:00:00"), value: 100},
                {date: new Date("2016-06-20 01:00:00"), value: 20},
                {date: new Date("2016-06-20 02:00:00"), value: 10},
                {date: new Date("2016-06-20 03:00:00"), value: 30},
                {date: new Date("2016-06-20 04:00:00"), value: 10},
                {date: new Date("2016-06-20 05:00:00"), value: 60},
                {date: new Date("2016-06-20 06:00:00"), value: 70},
                {date: new Date("2016-06-20 07:00:00"), value: 30},
                {date: new Date("2016-06-20 08:00:00"), value: 90},
                {date: new Date("2016-06-20 09:00:00"), value: 500},
                {date: new Date("2016-06-20 10:00:00"), value: 610},
                {date: new Date("2016-06-20 11:00:00"), value: 420},
                {date: new Date("2016-06-20 12:00:00"), value: 930},
                {date: new Date("2016-06-20 13:00:00"), value: 940},
                {date: new Date("2016-06-20 14:00:00"), value: 1150},
                {date: new Date("2016-06-20 15:00:00"), value: 760},
                {date: new Date("2016-06-20 16:00:00"), value: 870},
                {date: new Date("2016-06-20 17:00:00"), value: 580},
                {date: new Date("2016-06-20 18:00:00"), value: 790},
                {date: new Date("2016-06-20 19:00:00"), value: 400},
                {date: new Date("2016-06-20 20:00:00"), value: 810},
                {date: new Date("2016-06-20 21:00:00"), value: 220},
                {date: new Date("2016-06-20 22:00:00"), value: 230},
                {date: new Date("2016-06-20 23:00:00"), value: 240},
                {date: new Date("2016-06-20 24:00:00"), value: 250}
            ];
            $(document).ready(function () {
                var width = 1400;
                var height = 500;
                svg = d3.select("#svg").append("svg").attr("width", width).attr("height", height + 100);
                svg.on("wheel.zoom", function () {

                });
                //svg.append("circle").attr("cx", "50px").attr("cy", "50px").attr("r", "50px").attr("fill", "red");
                //var drag = d3.drag();
//                svg.on("click", function(d,i){
//                    console.debug(event);
//                });
//                drag.on("drag", function (d) {
//                    k++;
//                    domains = [new Date("2016-06-19 23:00:00"), new Date("2016-06-20 23:00:00")];
//                    var xScale = d3.scaleTime().domain(domains).range([0, 1200]);
//                    var xAxis = d3.axisBottom(xScale)
//                            .tickFormat(function (d) {
//                                return  d.getHours();
//                            }).ticks(24);
//                            
//                    gAxis.transition()
//                            .duration(100)
//                            .call(xAxis);
//                    //console.debug(event.movementX);
//                    MX += event.movementX;
//                    var aMX = Math.abs(MX);
//                    if(aMX > )
//                });
                //svg.call(drag);
                //var ticks = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24];
                //var xScale = d3.scale.linear().domain([0, 24]).range([0, 1000]);

                var xDomains = d3.extent(data, function (d) {
                    return d.date;
                });

                var yDomains = d3.extent(data, function (d) {
                    return d.value;
                });

                var xScale = d3.scaleTime().domain(xDomains).range([0, 1200]);
                //var axis = d3.svg.axis().scale(x).orient("bottom").tickFormat(zh.timeFormat("%Y%m%d %H"));

                var yScale = d3.scaleLinear().domain(yDomains).range([height, 0]).nice(2).clamp(true);

                var xAxis = d3.axisBottom(xScale)
                        .tickFormat(function (d) {
                            return  d.getHours();
                        }).ticks(24);

                var yAxis = d3.axisLeft(yScale);

                //var axis  = d3.svg.axis().scale(xScale).orient("bottom").tickValues(ticks);
                gAxis = svg.append("g").attr("transform", "translate(70," + (height + 10) + ")").attr("class", "axis");

                var gyAxis = svg.append("g").attr("class", "y axis").attr("transform", "translate(70,10)");

                xAxis(gAxis);
                yAxis(gyAxis);

                var line = d3.line()
                        .x(function (d) {
                            return xScale(d.date);
                        })
                        .y(function (d) {
                            console.debug(yScale(d.value));
                            return yScale(d.value);
                        });
                        
                svg.append("path")
                        .attr("class", "line")
                        .attr("d", line(data))
                        .attr("transform", "translate(70,10)");

                //$("#inner").draggable({axis: "x"});

            });


            function test() {
                var margin = {top: 30, right: 20, bottom: 30, left: 50};
                width = 600 - margin.left - margin.right;
                height = 270 - margin.top - margin.bottom;

                var parseDate = d3.time.format("%d-%b-%y").parse;

                var x = d3.time.scale().range([0, width]);
                var y = d3.scale.linear().range([height, 0]);

                var xAxis = d3.svg.axis().scale(x).orient("bottom").ticks(5);
                var yAxis = d3.svg.axis().scale(y).orient("left").ticks(5);

                //?
                var valueline = d3.svg.line()
                        .x(function (d) {
                            return x(d.date);
                        })
                        .y(function (d) {
                            return y(d.close);
                        });

                var svg = d3.select("body")
                        .append("svg")
                        .attr("width", width + margin.left + margin.right)
                        .attr("height", height + margin.top + margin.bottom)
                        .append("g")
                        .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

                //Get the data
                d3.tsv("data/data.tsv", function (error, data) {
                    data.forEach(function (d) {
                        d.date = parseDate(d.date);
                        d.close = +d.close;
                    });

                    //Scale(规模) the range of the data
                    x.domain(d3.extent(data, function (d) {
                        return d.date;
                    }));
                    y.domain([0, d3.max(data, function (d) {
                            return d.close;
                        })]);

                    //Add the valueline path
                    svg.append("path")
                            .attr("d", valueline(data));

                    //Add the X Axis
                    svg.append("g")
                            .attr("class", "x axis")
                            .attr("transform", "translate(0," + height + ")")
                            .call(xAxis);
                    //Add the Y Axis
                    svg.append("g")
                            .attr("class", "y axis")
                            .call(yAxis);
                });
            }

            function getData() {
                $.ajax({
                    url: "http://172.16.6.29:8010/dataservice/getconfig",
                    async: true,
                    type: 'POST',
                    data: {id: 1},
                    xhrFields: {
                        withCredentials: false
                    },
                    success: function (text, textStatus) {
                        try {
                            var o = $.parseJSON(text);
                            console.debug(o);
                        } catch (e) {
                            console.error(e);
                        }
                    }
                });
            }
        </script>
    </head>
    <body>  
        <div id="content">
            <div id="outer" style="width:700px;height:100px;border:1px solid red;overflow: hidden;display: none">
                <div id="inner" style="width:3000px;height:100px;background-color:#cccccc">

                </div>
            </div>
        </div>

        <div id="svg" style="width:1300px;height:700px;margin-top:150px;">

        </div>
    </body>

</html>
