<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=9">
        <title>恒大金服实时报表系统登录</title>

        <link rel="stylesheet" type="text/css" href="/js/semantic/semantic.min.css">
        <script type="text/javascript" src="/js/jquery.min.js"></script>
        <script src="/js/semantic/semantic.min.js"></script>
        <script src="/js/store.min.js"></script>
        <script src="/js/jquery.cookie.js"></script>

        <style>
            body {
                font-family: Verdana,Arial,Helvetica,sans-serif;
                margin: 0;
                background-color:#35b5d3;
                text-align: center;
                overflow: hidden;
            }
            .title{
                text-align: center;
                width: 100%;
                height: 100px;
                font-size: 60px;
                margin-top: 30px;
                line-height: 100px;
                color: #fff;
            }
            .ui.grid{
                margin:0;
            }
            .login-header {
                background-color: #0066b1;
            }

            .ui.white {
                color: #fff;
            }
            .text-center{
                text-align:center;
            }
            .ui.login-div{
                width:900px;
                margin:0 auto;
                padding:30px 50px;
                border-radius:15px;
                background-color: #fff
            }

            #message{
                font-weight:bolder
            }

            form div{
                margin-bottom: 15px;
            }

        </style>
        <script>
            var termType = String(navigator.platform).toLocaleLowerCase();

            $(document).ready(function () {

                if (window.localStorage) {
                    var sp = store.get("pp");
                    var cp = $.cookie("pp");
                    if (sp && !cp) {
                        $.cookie("pp", sp);
                        store.remove("pp");
                    }
                }

                var w = $(window).width();
                var h = $(window).height();

                if (termType === "iphone" || termType.indexOf("linux arm") >= 0) {//phone
                    $("#message").css("font-size", "30px");
                    var windowPer = w * 0.7;
                    $(".login-div").width(windowPer);
                } else if (termType.indexOf("mac") >= 0 || termType.indexOf("win") >= 0) {
                    $(".login-div").width(500);
                    $(".input").addClass("big").removeClass("massive");
                    $("#submit").css("font-size", "20px");
                    $(".title").css("font-size", "40px");
                } else {

                }

//                if (w > h) {//pc
//                    //console.debug("pc");
//                    alert(1);
//                    $(".login-div").width(500);
//                    $(".input").addClass("big").removeClass("massive");
//                    $("#submit").css("font-size", "20px");
//                    $(".title").css("font-size", "40px");
//                } else {//phone
//                    alert(2);
//                    //console.debug("!pc");
//                    $("#message").css("font-size", "30px");
//                    var windowPer = w * 0.7;
//                    $(".login-div").width(windowPer);
//                }

                var topHeight = (h - $(".login-div").height() - 60) / 2 - 50;
                var titleTopHeight = (topHeight - 100) * 0.2;

                $("#top").height(topHeight);
                $(".title-top").height(titleTopHeight);
                $("#submit").click(function () {
                    var name = $("#username").val().replace(/ /g, '');
                    var pass = $("#password").val().replace(/ /g, '');

                    if (name.length === 0 || pass.length === 0) {
                        $("#message").text("用户名密码不能为空");
                        return;
                    }

                    $.ajax({
                        url: "/login/doLogin",
                        async: true,
                        type: 'POST',
                        data: {name: name, pass: pass},
                        success: function (text, textStatus) {
                            var o = jQuery.parseJSON(text);
                            if (o.c === 0) {
                                try {
                                    store.set('pp', $.cookie("pp"));
                                    var a = $("<a></a>");
                                    a.attr("href", "/index");
                                    a.appendTo($("body"));
                                    a.hide();
                                    var span = $("<span>aaa</span>").appendTo(a);
                                    window.setTimeout(function(){
                                        span.trigger("click");
                                    },200);
                                } catch (e) {
                                    window.location.href = o.t;
                                }
                            } else if (o.c === -1) {
                                $("#message").text(o.t);
                            }
                        }
                    });
                });
            });

        </script>

    </head>
    <body>
        <div id="top">
            <div class="title-top"></div>
            <div class="title">
                恒大金服实时报表系统
            </div>
        </div>
        <div class="ui login-div stackable">
            <form id="login-form" class="ui fluid form">
                <div class="field">
                    <div id="message" style="color:red"></div>
                </div>
                <div class="field">
                    <div class="ui left icon input massive">
                        <input id="username" style="border: 2px solid #aaa" type="text" name="userName" placeholder="">
                        <i class="user icon"></i>
                    </div>
                </div>
                <div class="field">
                    <div class="ui left icon input massive">			
                        <input id="password" style="border: 2px solid #aaa" type="password" name="password" placeholder="">
                        <i class="lock icon"></i>
                    </div>
                </div>
                <div class=" field">
                    <div class="ui left">
                        <div id="submit" style="font-size:50px;" class="ui fluid blue submit button">登录</div>
                    </div>
                </div>
            </form>
        </div>
    </body>
</html>